---
development:
  cloud_name: dkhg31eh6
  api_key: '523885617334156'
  api_secret: YqJEBIm5OfxlHAlczWzIar-Wk4I
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dkhg31eh6
  api_key: '523885617334156'
  api_secret: YqJEBIm5OfxlHAlczWzIar-Wk4I
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dkhg31eh6
  api_key: '523885617334156'
  api_secret: YqJEBIm5OfxlHAlczWzIar-Wk4I
  enhance_image_tag: true
  static_file_support: false
